backend:
  name: git-gateway
  branch: main 
media_folder: "public/assets/img/uploads"
public_folder: "/assets/img/uploads"
collections:
  - name: "gallery"
    label: "Gallery"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "src/gallery-photos"
    fields:
      - {label: "Name", name: "title", widget: "string"}  
      - {label: "Tags", name: "tags", widget: "hidden", default: ["galleryPhoto"]}
      - {label: "Featured Image", name: "image", widget: "image"}  
      - {label: "Image alt test", name: "imageAlt", widget: "string"}  