backend:
  name: git-gateway
  branch: main 
# media_folder: "public/assets/img/uploads"
# public_folder: "/assets/img/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: d7aaead4c10cc686ec72
collections:
  - name: "gallery"
    label: "Gallery"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "src/gallery-photos"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}  
      - {label: "Tags", name: "tags", widget: "hidden", default: ["galleryPhoto"]}
      - {label: "Featured Image", name: "image", widget: "image"}  
      - {label: "Image alt test", name: "imageAlt", widget: "string"}  